on: [push]

jobs:
  testjob:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: release
        name: Release
        uses: tudorrrrrr/releases-workflow@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG
        run: echo -e "${{ steps.release.outputs.changelog }}\n$(cat CHANGELOG.md)" > CHANGELOG.md

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update CHANGELOG.md'
          push: true
          tag: ${{ steps.release.outputs.newTag }}
