on: [push]

jobs:
  testjob:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: release
        name: Release
        uses: tudorrrrrr/releases-workflow@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG
        run: |
          echo ${{ steps.release.outputs.newTag }}
          echo ${{ steps.release.outputs.changelog }}
