on: [push]

jobs:
  testjob:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Release
        uses: tudorrrrrr/releases-workflow@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
