on:
  push:
    branches:
      - main

jobs:
  testjob:
    runs-on: ubuntu-latest
    name: Update changelog version
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop

      - uses: tudorrrrrr/update-changelog-version@main
        with:
          filePath: './CHANGELOG.md'

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update CHANGELOG.md'
          branch: develop
          push: true
