on:
  push:
    branches:
      - main

jobs:
  testjob:
    runs-on: ubuntu-latest
    name: Update changelog version
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop

      - id: update-version
        uses: tudorrrrrr/update-changelog-version@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filePath: './CHANGELOG.md'

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update CHANGELOG.md for ${{ steps.update-version.outputs.newTag }}'
          branch: develop
          push: true

      - name: Notify
        uses: archive/github-actions-slack@v2.0.0
        if: ${{ steps.update-version.outputs.changelog != '' }}
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C022DKHB03U
          slack-text: ':rotating_light: *New release*\n\n${{ steps.update-version.outputs.changelog }}'
